### ISSUE TITLE
No produce el comportamiento requerido

### ISSUE THREAD

**Issue by gaal1le0** [DanBaDo/exercise-instagram-feed-bootstrap#1]
https://github.com/DanBaDo/exercise-instagram-feed-bootstrap/blob/6fdf1f2e9c1582678c098a5405ef6048dbb66405/index.html#L90

Si visualizas tu página completa verás que si haces scroll down hasta el final verás un hueco en blanco, tal y como te adjunto en la siguiente **imagen**.

![Captura de pantalla 2021-10-25 a las 16 35 47 (2)](https://user-images.githubusercontent.com/84098854/138715811-9a29908d-651b-46a8-8ab6-de3b33de4057.png)

Esto se debe a que tu has colocado una clase que se llama `d-flex` dentro de uno de los tabs que controla el div, esto por superposición elimina una propiedad dentro de `.tab-content>.tab-pane` que es display: none; lo que produce ese efecto de que la altura del contenedor es la **no** deseada. Para solucionar esto deberás cambiar la linea del ISSUE por la que yo te coloco.

```html
<div class="tab-pane fade" id="pillB" role="tabpanel" aria-labelledby="pills-B-tab">
```

Si haces eso, tu segunda vista quedará así:

![Captura de pantalla 2021-10-25 a las 16 37 45](https://user-images.githubusercontent.com/84098854/138716137-41101f84-446a-4cce-87cf-de528a310e40.png)

Como ves, el contenido se ha desplazado a la derecha, debes colocarlo en el centro sin usar nada de d-flex ni nada por el estilo, usa la imaginación :).

También pedirte que en la segunda tab entre cada card mangas algo de margin para que se separen un poco más (algo más estético de cara al público)

Además quería aprovechar este ISSUE para felicitarte por el diseño del ejercicio, te lo has currado bastante y la primera tab me encanta como se ve, esto si está bien pensado y estructurado.  De manera genérica el diseño esta **espectacular**

Cualquier duda ya sabes donde estoy :)

**Comment by DanBaDo** [comment]
No voy a decir que no me ha dado guerra.
He tenido que aprender a usar adecuadamente las convinaciones de .container .row .col
Despues de dar tantas vueltas no lo tengo muy claro, pero supongo que habrá más oportunidades para revisarlo.

**Comment by gaal1le0** [comment]
JAJAJA Suele pasar es un verdadero coñazo :)
Intenta solucionarlo y si quieres concretamos una mentoria por slack de 30 min para poder explicarte bien eso.

**Comment by DanBaDo** [comment]
Creo que está solucionado

**Comment by gaal1le0** [comment]
Okey. Envia la tarea a través de BreathCode para que pueda revisarla.
