### ISSUE TITLE
Falta title

### ISSUE THREAD

**Issue by gaal1le0** [DanBaDo/exercise-instagram-feed-bootstrap#2]
https://github.com/DanBaDo/exercise-instagram-feed-bootstrap/blob/0732b5f5f4c86b769e4efc320cf39cf623587089/index.html#L10.

De cara al SEO y a la entrega del proyecto evita poner ese title por defecto, JAJAJAJ siempre coloca uno que tenga relacion con el proyecto.

**Comment by DanBaDo** [comment]
Done
