### ISSUE TITLE
Faltan atributos alt

### ISSUE THREAD

**Issue by gaal1le0** [DanBaDo/exercise-instagram-feed-bootstrap#3]
https://github.com/DanBaDo/exercise-instagram-feed-bootstrap/blob/0732b5f5f4c86b769e4efc320cf39cf623587089/index.html#L64

En todas las imagenes del HTML faltan los atributos ALT. Recuerda que son importante para el tema de accesibilidad y que son 100% obligatorias, debes rellenarlas todas. 
Recuerda que es colocar una breve descripción del contenido de las imagenes.

**Comment by DanBaDo** [comment]
Done...
