### ISSUE TITLE
Imagenes sin atributo ALT

### ISSUE THREAD

**Issue by gaal1le0** [DanBaDo/exercise-instagram-feed-bootstrap#4]
https://github.com/DanBaDo/exercise-instagram-feed-bootstrap/blob/3d783dca7b6ed15265fa8b302b67b07bf8c5f9b1/index.html#L96

Recuerda completar todos los atributos ALT de las imagenes, te has dejado la mitad, a partir de esta linea hay más imagenes sin dichos atributos.

PD: No te olvides de cerrar los ISSUEs una vez lo hayas solucionado.

**Comment by DanBaDo** [comment]
Done
